### ISSUE TITLE
Django 1.9 compatibility

### ISSUE THREAD

**Issue by mrnfrancesco** [tubaman/django-macaddress#15]
Using your module with Django 1.8 I had the following warning:

```formfields.py:1: RemovedInDjango19Warning: The django.forms.util module has been renamed. Use django.forms.utils instead.```

**Comment by kra3** [comment]
That should be okay for now. 
Django keeps doing backward incompatible changes in almost every release :disappointed: 
By the time django 1.9 is released, I'll make a fix for this.

**Comment by kra3** [comment]
commit #16 should fix this warning.
